#!/usr/bin/env bash
#
# Creates the Terraform remote state bucket and writes infra/backend.hcl.
#
# This is the one thing that cannot be Terraform: the backend has to exist
# before Terraform can use it. Run it once per account, then never again --
# it is idempotent and safe to re-run.
#
#   ./scripts/bootstrap-state.sh
#   terraform -chdir=infra init -backend-config=backend.hcl
#
# No DynamoDB lock table. Terraform 1.10+ locks S3 state with conditional
# writes (`use_lockfile = true` in versions.tf), which removes a resource that
# used to be mandatory boilerplate -- and one more thing to forget to destroy.

set -euo pipefail

REGION="${AWS_REGION:-us-east-1}"
PROJECT="${PROJECT:-fraud-api}"

ACCOUNT_ID="$(aws sts get-caller-identity --query Account --output text)"
BUCKET="${TF_STATE_BUCKET:-${PROJECT}-tfstate-${ACCOUNT_ID}}"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BACKEND_FILE="${REPO_ROOT}/infra/backend.hcl"

echo "Account : ${ACCOUNT_ID}"
echo "Region  : ${REGION}"
echo "Bucket  : ${BUCKET}"
echo

if aws s3api head-bucket --bucket "${BUCKET}" 2>/dev/null; then
  echo "Bucket already exists; reapplying settings."
else
  echo "Creating bucket."
  # us-east-1 is the odd one out: passing a LocationConstraint of us-east-1 is
  # an error, while omitting it anywhere else silently creates the bucket in
  # us-east-1.
  if [ "${REGION}" = "us-east-1" ]; then
    aws s3api create-bucket --bucket "${BUCKET}" --region "${REGION}" >/dev/null
  else
    aws s3api create-bucket --bucket "${BUCKET}" --region "${REGION}" \
      --create-bucket-configuration "LocationConstraint=${REGION}" >/dev/null
  fi
  aws s3api wait bucket-exists --bucket "${BUCKET}"
fi

# Versioning is not a nicety here. State is the only record of what exists in
# the account; a corrupted or truncated write with no previous version is an
# afternoon of importing resources by hand.
aws s3api put-bucket-versioning \
  --bucket "${BUCKET}" \
  --versioning-configuration Status=Enabled

aws s3api put-bucket-encryption \
  --bucket "${BUCKET}" \
  --server-side-encryption-configuration '{
    "Rules": [{
      "ApplyServerSideEncryptionByDefault": {"SSEAlgorithm": "AES256"},
      "BucketKeyEnabled": true
    }]
  }'

# State files contain every attribute of every resource. Nothing about this
# bucket should ever be public.
aws s3api put-public-access-block \
  --bucket "${BUCKET}" \
  --public-access-block-configuration \
    "BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true"

aws s3api put-bucket-ownership-controls \
  --bucket "${BUCKET}" \
  --ownership-controls 'Rules=[{ObjectOwnership=BucketOwnerEnforced}]'

# Old state versions are tiny but unbounded; expire them rather than keeping
# every plan's worth forever.
aws s3api put-bucket-lifecycle-configuration \
  --bucket "${BUCKET}" \
  --lifecycle-configuration '{
    "Rules": [{
      "ID": "expire-noncurrent-state",
      "Status": "Enabled",
      "Filter": {"Prefix": ""},
      "NoncurrentVersionExpiration": {"NoncurrentDays": 30},
      "AbortIncompleteMultipartUpload": {"DaysAfterInitiation": 7}
    }]
  }'

cat > "${BACKEND_FILE}" <<EOF
# Generated by scripts/bootstrap-state.sh -- do not edit by hand.
# Bucket names are globally unique and this one embeds an account id, so it is
# machine-specific and gitignored. Re-run the script to regenerate it.
bucket = "${BUCKET}"
region = "${REGION}"
EOF

echo
echo "Wrote ${BACKEND_FILE}"
echo
echo "Next:"
echo "  terraform -chdir=infra init -backend-config=backend.hcl"
echo "  terraform -chdir=infra plan -var-file=envs/prod.tfvars"
